name: Cloud Functions Deploy
description: Deploy Cloud Functions
author: GoogleCloudPlatform

inputs:
  credentials:
    description: |-
      Optional service account key to use for authentication to Cloud Functions. This should be the JSON
      formatted private key which can be exported from the Cloud Console. The
      value can be raw or base64-encoded.
    required: false
  name:
    description: |-
      Name of the Cloud Function.
    required: true
  description:
    description: |-
      Description for the CF.
    required: false
  project_id:
    description: |-
      Project to deploy the function in.
    required: true
  source_dir:
    description: |-
      Path to function deployment directory within the source repo.
    required: false
  env_vars:
    description: |-
      List of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.
    required: false
  entry_point:
    description: |-
      Name of function to execute.
    required: false
  runtime:
    description: |-
      Runtime to use for the function.
    required: true
  vpc_connector:
    description: |-
      The VPC Access connector that the function can connect to.
    required: false
  service_account_email:
    description: |-
      The email address of the IAM service account associated with the function at runtime.
    required: false
  timeout:
    description: |-
      The function execution timeout.
    required: false
  max_instances:
    description: |-
      The maximum number of instances for the function.
    required: false
  event_trigger_type:
    description: |-
      Specifies which action should trigger the function.
    required: false
  event_trigger_resource:
    description: |-
      Specifies which resource from eventTrigger is observed.
    required: false
  event_trigger_service:
    description: |-
      The hostname of the service that should be observed.
    required: false

runs:
  using: "node12"
  main: "dist/index.js"